language: node_js

node_js:
  - node

addons:
#  postgresql: "9.6"
  chrome: stable
#  apt:
#    sources:
#      - mysql-5.7-trusty
#      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'
#        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
#    packages:
#      - mysql-client
#      - mysql-server
#      - mssql-server
#      - mssql-tools

services:
#  - mysql
  - docker

before_install:
#  - sudo mysql_upgrade
#  - mysql -v -e "source test/mysql/db_create.sql"
#  - mysql -v -e "source test/mysql/expecteddatamodel_table_create.sql"
#  - psql -v ON_ERROR_STOP=1 --username postgres -f test/postgreqsl/db_create.sql
#  - psql -v ON_ERROR_STOP=1 --username user -f test/postgreqsl/expecteddatamodel_table_create.sql
#  - sudo chmod 777 /etc/postgresql/9.6/main/pg_hba.conf
#  - sudo sed -i '/\bhost    all             all             127.0.0.1\/32            trust\b/i host    all             user            all                      md5' /etc/postgresql/9.6/main/pg_hba.conf
#  - sudo chmod 640 /etc/postgresql/9.6/main/pg_hba.conf
#  - sudo service postgresql restart 9.6
  - docker-compose -f test/postgresql/docker-compose.yml up -d db
  - docker-compose -f test/mssql/docker-compose.yml up -d db
  - docker-compose -f test/mysql/docker-compose.yml up -d db

#jobs:
#  include:
#    - stage: Produce Coverage
#      node_js: node
#      script: jest --detectOpenHandles --passWithNoTests --coverage --coverageReporters=text-lcov | coveralls

before_deploy:
  - export PKG_NAME=$(node -p -e "require('./package.json').name")
  - export PKG_VERSION=$(node -p -e "require('./package.json').version")
  - npm install -g mkdirp
  - npm prune --production
  - mkdirp ./dist -m 0777
  - mkdirp ./$PKG_NAME -m 0777
  - cp *.js package.json README.md LICENSE ./$PKG_NAME
  - cp -r ./db ./erd ./keymaps ./menus ./mssql ./mysql ./node_modules ./polyfill ./postgresql ./preferences ./util ./$PKG_NAME
  - zip -r ./dist/$PKG_NAME-$PKG_VERSION.zip ./$PKG_NAME

after_success:
  - npm run coveralls
  - npm run snyk-monitor

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  on:
    repo: kkrisz1/staruml-reverse-db
    tags: true
  file_glob: true
  file: dist/*
  skip_cleanup: true

cache:
  directories:
    - node_modules
